spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: application-service
          uri: lb://application-service
          predicates:
            - Path=/application-service/**

        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee-service/**

        - id: housing-service
          uri: lb://housing-service
          predicates:
            - Path=/housing-service/**

#        - id: email-service
#          uri: lb://email-service
#          predicates:
#            - Path=/email-service/**


server:
  port: 8000


eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
